# Quick Start
# $ xhost local:root
# $ docker compose up

services:
  plotjuggler-ros:
    image: husarion/plotjuggler:humble
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY
    command: ros2 run plotjuggler plotjuggler

  talker:
    build:
      context : .
      dockerfile: Dockerfile.chatter
    command: ros2 run demo_nodes_cpp talker

  listener:
    build:
      context : .
      dockerfile: Dockerfile.chatter
    command: ros2 run demo_nodes_cpp listener